services:
  okta-scim-fastify:
    container_name: okta-scim-fastify
    build: .
    env_file:
      - .env
    ports:
      - "${PORT:-8011}:${PORT:-8011}"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - haproxy

networks:
  haproxy:
    external: true



